name: notat-api-CI

on:
  push:
    branches: [ master ]
    # paths: 
    #   - 'notat-api/**'

  pull_request:
    branches: [ master ]
    paths: 
      - 'notat-api/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      
      - name: Build with Gradle
        run: ./notat-api/gradlew --project-dir=notat-api build

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: mapster
          password: ${{ secrets.CR_PAT }}
          registry: ghcr.io
          repository: cx-devops-101/notes-app/notat-api
          path: notat-api
          tag_with_sha: true
          push: ${{github.ref == 'refs/heads/master'}}